### ISSUE TITLE
Initial solution code review

### ISSUE THREAD

**Issue by merdacz** [SzmergieL/PhoneBook#1]
1. The API exposes to much operations, e.g. there is not need for adding dangling phones nor getting phone by id 
or searching for users. The API should expose only the requested operations no more no less.  
2. Same goes for all operations for maintaining users. Those are handled by another library as should not be concern of the one you build. Each user authenticates via Guid and should have access only to his phone book. 
3. I think you got the model wrong. Each user can maintain his own phone book and individual users should not "share" phone entries. Also entries should have name. User names are not our concern in this library. For example myself I have a phone book with entries "John Smith, mobile, 123456" and "Amy Smith, mobile, 654321" and your user may have "Johnny Smith, mobile, 123456" and "John Smith, mobile, 111111". Totally separate. This in particular means you should not 
check phone number uniqueness across users in your add phone routine and also that Phone should not refer 
multiple Users in your model. 
4. Similarly searching for contract entries, should be always in the context of the User and allow filtering by both first and last name, not only one of those. At minimum we need partial matches (stats with like) but preferably we would have option for phonetic search. The result may be limited to 10 top entries (alphabetical order) to avoid loading the whole database. 
5. I would reconsider exposing EF entities from the API. We don't want dynamic proxies to cross logical boundaries. As you
noted yourself some things simply would not work or work. Instead DTO should be used. Alongside with IphoneBookApi they would constitute the contract that separates/facades the concrete implementation. 
6. Since the developers would need to learn how to use the library we need some examples. Preferably in form of unit/integration tests (using framework of your choice). Such suite would also serve the purpose of the library self-verification.

**Comment by SzmergieL** [comment]
3) This is proposition of new database schema

![schema2](https://cloud.githubusercontent.com/assets/5410643/9971175/2748669e-5e5a-11e5-807b-1fcc553882a3.png)

- **OwnerGUID** - would be guid of phone book owner, allowing us to query data only from his phone book. Or maybe I'm still not getting it - and when you say "Each user can maintain his own phone book" you actually mean separate databases, and there is no need for owner guid field in db?
- Since combination of the first and last name of person (in contact list) is not unique across whole database, and considering there is no need to distinguish between "John Doe" from "A" phone book and "John Doe" from "B" phone book, I feel like there is no need to make separate table for person

4) Do you have any specific phonetic search algorithm in mind? I have no prior experience with phonetic search algorithms and I would have to research the topic first.

**Comment by merdacz** [comment]
The new proposed schema looks good. I agree single table should be enough here. And no, we do not want separate database for each user. In future if we have high number of users we may consider scaling up by horizontal partitioning or sharding. This however is not part of the task for now. 

As of phonetic match algorithms Soundex is the simplest and is directly supported in SQL Server. Another example is metaphone, which is improvement over Soundex. In general we expect some algorithm tweaking in future, so you may choose something simple at this point (even something close to identity function) as long as we can easily switch this to new implementation in future.
